RevatureBAM/BAMPhoenix

- STUB/src/main/java/com/revature/beans/Curriculum.java
- STUB/src/main/java/com/revature/controllers/CurriculumController.java
- STUB/src/main/java/com/revature/dao/CurriculumRepository.java
- STUB/src/main/java/com/revature/service/Service.java
was able to view curriculum from browser on last run
> changed curriculum naming

- STUB/src/main/resources/log4j.properties
Made some change to log4j properties file for Teresa.
> Changed log4j properties for Teresa

- BAM/src/main/webapp/index.html
- BAM/src/main/webapp/static/controller/batchesOtherController.js
- BAM/src/main/webapp/static/css/main.css
- BAM/src/main/webapp/static/js/app.js
- BAM/src/main/webapp/static/pages/batchesAll.html
- BAM/src/main/webapp/static/pages/batchesFuture.html
- BAM/src/main/webapp/static/pages/batchesPast.html
> Batch tabs progress

- BAM/pom.xml
- BAM/src/main/java/com/bam/controller/UserController.java
> Added Update Method

- BAM/src/main/java/com/bam/beans/Users.java
- BAM/src/main/webapp/static/controller/updateAssociateController.js
> Fixed update

- BAM/src/main/java/com/bam/dao/BatchRepository.java
- BAM/target/test-classes/README.md
Removed imports that are already imported from java.lang
> refactored BatchRepo

- BAM/src/main/webapp/static/css/main.css
just added back in the overflow for calander - tested already therefore the PR is into develop not testing
> fixed overflow

- BAM/src/main/webapp/static/css/main.css
Reverts RevatureBAM/BAMPhoenix#204
> Revert "Calendar view design and colors"

- BAM/src/main/webapp/WEB-INF/applicationContext.xml
Reverts RevatureBAM/BAMPhoenix#207
> Revert " addign changes to xml file"

- BAM/src/main/webapp/WEB-INF/applicationContext.xml
Reverts RevatureBAM/BAMPhoenix#208
> Revert "Revert " addign changes to xml file""

- BAM/src/main/java/com/bam/controller/UserController.java
- BAM/src/main/java/com/bam/service/EmailRun.java
- BAM/src/main/java/com/bam/service/MailService.java
- BAM/src/main/java/com/bam/service/UsersDetailsService.java
- BAM/src/main/webapp/static/controller/calendarController.js
- BAM/src/main/webapp/static/controller/navController.js
- BAM/src/main/webapp/static/js/fullcalendar.js
- BAM/src/main/webapp/static/js/service.js
- BAM/src/main/webapp/static/pages/EditBatch.html
- BAM/src/main/webapp/static/pages/calendar.html
Reverts RevatureBAM/BAMPhoenix#221
> Revert "Merge test branch"

- BAM/src/main/webapp/static/controller/calendarController.js
We will need to test this both normally in develop and with different timezones in develop.
> Fixed Bug where calendar shows partial week numbers

- BAM/src/main/java/com/bam/controller/CalendarController.java
- BAM/src/main/java/com/bam/repository/SubtopicRepository.java
- BAM/src/main/java/com/bam/service/SubtopicService.java
- BAM/src/main/webapp/index.html
- BAM/src/main/webapp/static/controller/calendarController.js
- BAM/src/main/webapp/static/controller/loginController.js
- BAM/src/main/webapp/static/js/subtopicService.js
- BAM/src/main/webapp/static/pages/EditBatch.html
Reverts RevatureBAM/BAMPhoenix#258
> Revert "Revert "Merge pagination into develop""

- BAM/src/main/java/com/bam/controller/UserController.java
- BAM/src/main/java/com/bam/security/SecurityConfig.java
- BAM/src/main/java/com/bam/service/EmailRun.java
- BAM/src/main/java/com/bam/service/MailService.java
- BAM/src/main/java/com/bam/service/UsersDetailsService.java
Reverts RevatureBAM/BAMPhoenix#278
> Revert "Hashing password"

- BAM/src/main/java/com/bam/bean/BamUser.java
- BAM/src/main/java/com/bam/service/UsersDetailsService.java
> Consume assignforce branch

- BAM/src/main/java/com/bam/repository/SubtopicRepository.java
- BAM/src/main/webapp/index.html
- BAM/src/main/webapp/static/controller/noBatchController.js
- BAM/src/main/webapp/static/pages/NoBatch.html
navbar was not showing with associates that had no batch assign to, i.e jonny@java.com com
>  adding navbar to associate who does not have a batch

- BAM/src/main/java/com/bam/security/SecurityConfig.java
- BAM/src/main/webapp/WEB-INF/web.xml
- BAM/src/main/webapp/index.html
- BAM/src/main/webapp/static/js/app.js
- BAM/src/main/webapp/static/js/googleAnalytics.js
- BAM/src/main/webapp/static/js/service.js
Reverts RevatureBAM/BAMPhoenix#304
> Revert "Revert "Merge Analytics into develop""

- BAM/pom.xml
- BAM/src/main/java/com/bam/bean/CurriculumSubtopic.java
- BAM/src/main/java/com/bam/bean/CustomException.java
- BAM/src/main/java/com/bam/controller/CalendarController.java
- BAM/src/main/java/com/bam/controller/CurriculumController.java
- BAM/src/main/java/com/bam/controller/UserController.java
- BAM/src/main/java/com/bam/dto/CurriculumSubtopicDTO.java
- BAM/src/main/java/com/bam/dto/DaysDTO.java
- BAM/src/main/java/com/bam/dto/WeeksDTO.java
- BAM/src/main/java/com/bam/logging/LoggerClass.java
- BAM/src/main/java/com/bam/service/EmailRun.java
- BAM/src/main/java/com/bam/service/MailService.java
- BAM/src/main/java/com/bam/service/SubtopicService.java
- BAM/src/main/java/com/bam/service/UsersDetailsService.java
- BAM/src/main/webapp/static/controller/curriculumController.js
Reverts RevatureBAM/BAMPhoenix#307
> Revert "Merging Roktim's code fixes and code smell fixes into Develop."

- BAM/pom.xml
- BAM/src/main/java/com/bam/bean/CurriculumSubtopic.java
- BAM/src/main/java/com/bam/bean/CustomException.java
- BAM/src/main/java/com/bam/controller/CalendarController.java
- BAM/src/main/java/com/bam/controller/CurriculumController.java
- BAM/src/main/java/com/bam/controller/UserController.java
- BAM/src/main/java/com/bam/dto/CurriculumSubtopicDTO.java
- BAM/src/main/java/com/bam/dto/DaysDTO.java
- BAM/src/main/java/com/bam/dto/WeeksDTO.java
- BAM/src/main/java/com/bam/logging/LoggerClass.java
- BAM/src/main/java/com/bam/service/EmailRun.java
- BAM/src/main/java/com/bam/service/MailService.java
- BAM/src/main/java/com/bam/service/SubtopicService.java
- BAM/src/main/java/com/bam/service/UsersDetailsService.java
- BAM/src/main/webapp/static/controller/curriculumController.js
Reverts RevatureBAM/BAMPhoenix#308
> Revert "Revert "Merging Roktim's code fixes and code smell fixes into Develop.""

- BAM/src/main/java/com/bam/logging/LoggerClass.java
- BAM/src/main/resources/log4j.properties
- BAM/src/main/webapp/static/js/app.js
Reverts RevatureBAM/BAMPhoenix#334
> Revert "Revert "Merge test branch""

- BAM/src/main/java/com/bam/logging/LoggerClass.java
- BAM/src/main/resources/log4j.properties
- BAM/src/main/webapp/static/js/app.js
Reverts RevatureBAM/BAMPhoenix#335
> Revert "Revert "Revert "Merge test branch"""

- BAM/src/main/java/com/bam/logging/LoggerClass.java
- BAM/src/main/java/com/bam/service/BamUserService.java
- BAM/src/main/resources/log4j.properties
- BAM/src/main/webapp/static/js/app.js
Reverts RevatureBAM/BAMPhoenix#332
> Revert "Logging"

- BAM/src/main/java/com/bam/logging/LoggerClass.java
- BAM/src/main/java/com/bam/service/BamUserService.java
- BAM/src/main/resources/log4j.properties
- BAM/src/main/webapp/static/js/app.js
Reverts RevatureBAM/BAMPhoenix#337
> Revert "Revert "Logging""

- BAM/src/main/java/com/bam/logging/LoggerClass.java
- BAM/src/main/resources/log4j.properties
- BAM/src/main/webapp/static/js/app.js
Reverts RevatureBAM/BAMPhoenix#336
> Revert "Revert "Revert "Revert "Merge test branch""""

- BAM/src/main/java/com/bam/service/MailService.java
Reverts RevatureBAM/BAMPhoenix#339
> Revert "swapped email info with enviroment variables"

- BAM/src/main/webapp/static/controller/curriculumController.js
- BAM/src/main/webapp/static/pages/curriculum.html
fixed some UX problems with the download button
> Curriculum v2

- BAM/src/main/webapp/static/css/main.css
Fixed the submit button and spaced out the logo and button. Can't figure out the weird sizes of the dropdown menus for subtopics.
> Styled the Subtopic page.

- BAM/pom.xml
- BAM/src/main/java/com/bam/controller/CurriculumController.java
- BAM/src/test/java/com/bam/controller/unit/CurriculumControllerTest.java
Reverts RevatureBAM/BAMPhoenix#450
> Revert "Revert "Merge Nam's Curriculum test cases into develop.""

- BAM/src/main/webapp/static/controller/SubtopicAddController.js
- BAM/src/main/webapp/static/pages/addSubtopic.html
Fixing alert class color so that if it is successful it will be green and if it fails it will be red.
To test, just submit a subtopic successfully and then add one on a date that already has that subtopic in order to see both alerts.
> Fixing addsubtopic
